version: '3.8'
services:
  syncify:
    build: .
    image: syncify
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
